wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.4
    cli_version: 0.15.12
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1698311895.791467
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 19
      - 23
      4: 3.11.4
      5: 0.15.12
      8:
      - 1
      - 4
      - 5
      13: darwin-arm64
learning_rate:
  desc: null
  value: 0.001
batch_size:
  desc: null
  value: 256
epochs:
  desc: null
  value: 1000
input_size:
  desc: null
  value: 26
embedding_size:
  desc: null
  value: 50
enc_hidden_size:
  desc: null
  value: 50
encoding_size:
  desc: null
  value: 200
dec_hidden_size:
  desc: null
  value: 100
output_size:
  desc: null
  value: 26
